mur:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

  arm_base_to_link_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: base_joint
      pid: {p: 100.0, i: 10.0, d: 0.0}